"""
Small SPARQL runner for the KG exploitation zone.

It loads the Turtle graph generated by scripts/exploitation_zone.py and executes
a .sparql query file. This is the first smoke test for the data analysis pipeline.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from rdflib import Graph


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TURTLE_PATH = PROJECT_ROOT / "exploitation_zone.ttl"
DEFAULT_QUERY_PATH = PROJECT_ROOT / "queries" / "sparql_smoke_test.sparql"


def iter_query_paths(query_path: Path) -> list[Path]:
    if query_path.is_dir():
        return sorted(query_path.glob("*.sparql"))
    return [query_path]


def format_cell(value: object) -> str:
    if value is None:
        return ""
    text = str(value)
    return text.replace("https://example.org/bda/nyc-mobility-safety/", "ex:")


def write_csv(output_dir: Path, query_path: Path, variables: list[str], rows: list[tuple[object, ...]]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{query_path.stem}.csv"

    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(variables)
        for row in rows:
            writer.writerow([format_cell(value) for value in row])

    print(f"CSV written: {output_path}")


def run_queries(turtle_path: Path, query_path: Path, output_dir: Path | None = None) -> None:
    if not turtle_path.is_file():
        raise FileNotFoundError(f"Turtle file not found: {turtle_path}")

    query_paths = iter_query_paths(query_path)
    missing_paths = [path for path in query_paths if not path.is_file()]
    if missing_paths:
        raise FileNotFoundError(f"SPARQL query file not found: {missing_paths[0]}")

    graph = Graph()
    graph.parse(turtle_path, format="turtle")
    print(f"Loaded triples: {len(graph)}")

    for current_query_path in query_paths:
        query = current_query_path.read_text(encoding="utf-8")
        results = graph.query(query)
        variables = [str(var) for var in results.vars]
        rows = list(results)

        print()
        print(f"Query file: {current_query_path}")
        print(f"Rows returned: {len(rows)}")
        print("\t".join(variables))

        for row in rows:
            print("\t".join(format_cell(value) for value in row))

        if output_dir is not None:
            write_csv(output_dir, current_query_path, variables, rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a SPARQL query over exploitation_zone.ttl")
    parser.add_argument(
        "--ttl",
        type=Path,
        default=DEFAULT_TURTLE_PATH,
        help="Path to the Turtle KG file.",
    )
    parser.add_argument(
        "--query",
        type=Path,
        default=DEFAULT_QUERY_PATH,
        help="Path to a .sparql query file or a directory with .sparql files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Optional directory where query results are written as CSV files.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    output_dir = args.output_dir.resolve() if args.output_dir else None
    run_queries(args.ttl.resolve(), args.query.resolve(), output_dir)
